//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6.DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dyd_bs_MQ_logEntities : DbContext
    {
        public dyd_bs_MQ_logEntities()
            : base("name=dyd_bs_MQ_logEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_debuglog> tb_debuglog { get; set; }
        public virtual DbSet<tb_error> tb_error { get; set; }
        public virtual DbSet<tb_log> tb_log { get; set; }
    }
}
