//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_debuglog
    {
        public long id { get; set; }
        public int mqpathid { get; set; }
        public string mqpath { get; set; }
        public string methodname { get; set; }
        public string info { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
